# Generated by Django 5.2.6 on 2026-03-14 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LastStreakReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastReset', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_question', models.CharField(max_length=300)),
                ('correct_answer', models.CharField(max_length=300)),
                ('source_language', models.CharField(default='Spanish', max_length=50)),
                ('target_language', models.CharField(default='English', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('firstName', models.CharField(default='', max_length=50)),
                ('lastName', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('dateJoined', models.DateField(auto_now_add=True)),
                ('streakCount', models.IntegerField(default=0)),
                ('longestStreak', models.IntegerField(default=0)),
                ('hasCompletedQuiz', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('length', models.IntegerField(default=5)),
                ('difficulty', models.CharField(default='Easy', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('correct_count', models.IntegerField(default=0)),
                ('incorrect_count', models.IntegerField(default=0)),
                ('curr_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.question')),
                ('questions', models.ManyToManyField(related_name='quiz_questions', to='home.question')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.member')),
            ],
        ),
        migrations.CreateModel(
            name='WordOfTheDayTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languagesGenerated', models.TextField(blank=True, default='')),
                ('languagesCompleted', models.TextField(blank=True, default='')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.member')),
            ],
        ),
    ]
